export const isVehicleTurning = (direction, newDirection) =>
     (direction === 'up' && newDirection === 'left')
  || (direction === 'up' && newDirection === 'right')
  || (direction === 'up' && newDirection === 'up-left')
  || (direction === 'up' && newDirection === 'up-right')
  || (direction === 'up-right' && newDirection === 'up-left')
  || (direction === 'up-right' && newDirection === 'down-right')
  || (direction === 'right' && newDirection === 'up')
  || (direction === 'right' && newDirection === 'down')
  || (direction === 'down-right' && newDirection === 'up-right')
  || (direction === 'down-right' && newDirection === 'down-left')
  || (direction === 'down' && newDirection === 'right')
  || (direction === 'down' && newDirection === 'left')
  || (direction === 'down' && newDirection === 'down-right')
  || (direction === 'down' && newDirection === 'down-left')
  || (direction === 'down-left' && newDirection === 'down-right')
  || (direction === 'down-left' && newDirection === 'up-left')
  || (direction === 'left' && newDirection === 'down')
  || (direction === 'left' && newDirection === 'up')
  || (direction === 'up-left' && newDirection === 'down-left')
  || (direction === 'up-left' && newDirection === 'up-right')
