export const characterPrototype = {
  id: null,
  type: 'character',
  name: 'Fred',
  status: 'alive',
  playerId: null,
  latency: null,
  drivingId: null,
  passengingId: null,
  occupyingId: null,
  vehicleMasterKeys: [],
  vehicleKeys: [],
  vehicleWelcomeIds: [],
  roomMasterKeys: [],
  roomKeys: [],
  x: null,
  y: null,
  width: 70,
  height: 103,
  depth: 1,
  direction: 'right',
  speed: null,
  maxSpeed: 10,
  isActive: false,
  tag: 'img',
  elementId: null,
  src: 'images/characters/man.png'
}
